### ISSUE TITLE
Mvnrepository icon

### ISSUE THREAD

**Issue by Zahorodnii** [gurock/testrail-junit-extensions#1]
Please forgive me for such a stupid question and even more so off-topic. I am developing a client API library for Java. And I noticed that you have a logo for the artifact on mvnrepository.com. Please tell me how did you do it. I have been looking for an answer to this question for 3 months now, but there is no documentation below. Thanks in advance.

**Comment by bitcoder** [comment]
Hi, it's a bit off-topic. You should ask this in StackOverflow for example, or other community.
Anyway, I don't know the answer.
Closing the issue.
