### ISSUE TITLE
Using annotation @TestRail(id = "C123") add property with key "case_id" that does not match property key "test_id" required by testrail-cli

### ISSUE THREAD

**Issue by Nerthal** [gurock/testrail-junit-extensions#2]
According to the test rail specification (https://github.com/gurock/trcli#2-using-case-id-specification-first-approach) property used to find test rail cases by id is named "test_id". However when using annotation @TestRail and giving case id in the xml report property with a key "case_id" is added making this annotation unusable (https://github.com/gurock/testrail-junit-extensions#testrail-annotation).

Can you update this annotation to use the property key supported by the cli?

**Comment by kopytovskiy** [comment]
Also faced with a same issue. @d-rede could you please have a look?

**Comment by kopytovskiy** [comment]
https://github.com/gurock/testrail-junit-extensions/pull/3

I have added the changes to a project. @d-rede could you check this MR please?

**Comment by d-rede** [comment]
Hello @kopytovskiy 
I'm no longer the maintainer of this project. @bitcoder should follow-up on the issue.

**Comment by bitcoder** [comment]
On it!

**Comment by bitcoder** [comment]
A quick analysis tells that trcli uses the property "test_id". I left some few comments on your PR. Can you please have a look at it?
