### ISSUE TITLE
Unable to set a property containing line breaks and have it preserved in TestRail

### ISSUE THREAD

**Issue by devinbileck** [gurock/testrail-junit-extensions#6]
For example, I would like to define test case steps separated by line breaks:
```java
@ExtendWith(TestRailTestReporterParameterResolver.class)
public class SumTests {
    
    @Test
    public void canAddNumbers(TestRailTestReporter customReporter) {
        customReporter.setProperty("testrail_case_field", "custom_steps:1. First step\n2. Second step\n3. Third step");
    }
}
```

The line breaks are preserved in the xml file:
```xml
<property name="testrail_case_field" value="custom_steps:1. First step
2. Second step
3. Third step"/>
```

But the line breaks are normalized to a space when uploaded to TestRail using TR CLI:
`1. First step 2. Second step 3. Third step`

Line breaks seem to be valid for XML attribute values, but XML parsers tend to normalize them to spaces.

I manually replaced the line breaks with `&#xA;` in the xml file and the line breaks were preserved in TestRail.
However, when trying to use `&#xA;` when setting the property:
```java
customReporter.setProperty("testrail_case_field", "custom_steps:1. First step&#xA;2. Second step&#xA;3. Third step");
```

It escapes the ampersand and replaces it with &amp;#xA;
`1. First step&#xA;2. Second step&#xA;3. Third step`

A possible solution could be when writing an attribute value, replace line breaks with `&#xA;` after escaping illegal characters:
https://github.com/gurock/testrail-junit-extensions/blob/main/src/main/java/com/testrail/junit/customjunitxml/XmlReportWriter.java#L502

**Comment by bitcoder** [comment]
1. From my understanding, adding newlines in an attribute is ok but the API should persist them encoded like 

`First step&#10;2. Second step&#10;3. Third step`

Right?
Therefore, this library should ensure that this gets properly encoded.. correct?

2. If we get the previous behaviour implemented, the TR CLI will process it fine?

**Comment by bitcoder** [comment]
@devinbileck can you please try with the code from the `encode_somechars_on_value_attributes` branch?

**Comment by devinbileck** [comment]
Thanks @bitcoder.

Unfortunately it is escaping the ampersand when writing to the xml file.
For example:
`<property name="testrail_case_field_2" value="custom_steps:1. First step&amp;#10;2. Second step"/>`

After uploading via TR CLI, it shows up in TestRail as:
`1. First step&#10;2. Second step`

Unfortunately your tests don't seem to catch this likely because it is un-escaping the parsed content. So it is not verifying against the actual content being written.

This seems to be the behaviour of the XMLStreamWriter writeAttribute method, where it will escape all ampersand characters.
As per https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLStreamWriter.html:
> The XMLStreamWriter interface specifies how to write XML. The XMLStreamWriter does not perform well formedness checking on its input. However the writeCharacters method is required to escape & , < and > For attribute values the writeAttribute method will escape the above characters plus " to ensure that all character content and attribute values are well formed. Each NAMESPACE and ATTRIBUTE must be individually written.

It seems the writeCharacters method would need to be used instead.

**Comment by bitcoder** [comment]
Thanks for the feedback. From your experiments, what would be a junit xml  output that needs to be produced so it works ahead with the cli?

**Comment by devinbileck** [comment]
It needs to write the following to the xml file:
`<property name="testrail_case_field" value="custom_steps:1. First step&#10;2. Second step"/>`

When uploading via TR CLI, it will correctly show up in TestRail as:
```
1. First step
2. Second step
```

I was able to get it to behave this way with these changes
[change.zip](https://github.com/gurock/testrail-junit-extensions/files/13603850/change.zip)

**Comment by bitcoder** [comment]
thanks. hope this solves it and doesn't break any existing behaviour

**Comment by bitcoder** [comment]
merged

**Comment by bitcoder** [comment]
thanks for your feedback and help @devinbileck . anything, please feel free to raise a new issue.
